version: '3.7'

services:
  gql:
    image: sails/gql:latest
    #command: ["yarn", "yarn build", "yarn start"]
    #working_dir: ./gql
    #env_file:
    #./gql/.env
    build:
      context: ./gql
      dockerfile: Dockerfile
    #ports:
        #- "4000:4000"
