input AccountInput {
  name: String
}

scalar DateTime

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  edit(input: AccountInput): User!
  login(input: LoginInput): User!
  signup(input: SignupInput): User!
}

type Query {
  logout: User!
  me: User
}

input SignupInput {
  email: String!
  name: String
  password: String!
  refer: String
}

type User {
  createdAt: DateTime!
  id: ID!
  updatedAt: DateTime!
}
