version: '3.7'
services:
  pg:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'sails'
      POSTGRES_DB: 'sails'
      POSTGRES_PASSWORD: 'sails'
    logging:
      driver: none
  # nginx:
  #   image: 'nginx'
  #   ports:
  #     - '80:80'
  #     - '443:443'